### ISSUE TITLE
shpPath paramater in Shapefile.WriteAllFeatures does not work

### ISSUE THREAD

**Issue by kronetix** [NetTopologySuite/NetTopologySuite.IO.Esri#2]
No matter what is supplied for shpPath the files are always written to the same directory the executable is in.

**Comment by DGuidi** [comment]
can you add some sample code that reproduces the error?

**Comment by kronetix** [comment]
When a path is specified for the shpPath parameter, WriteAllFeatures does not write the files to that path. 

Instead, it seems to use the last folder in the path and use this as the filenames, it then writes the files to the same directory the executable is running from.

So there is no way to control where the files are written.

There is no error, it is just not the desired behavior.

![image](https://user-images.githubusercontent.com/105649582/168699490-0d3b19ca-2ad4-4eef-ad97-365d2899074a.png)

![image](https://user-images.githubusercontent.com/105649582/168699622-e805c38e-52c4-4a48-b293-6044428c1d0f.png)

Cheers

**Comment by DGuidi** [comment]
The path you uses basically means that you want to create a file named "test" in the CurrentDirectory. This is the expected behaviour because the path parameter must be the path to a file.

You can immedately fix this problem using this procedure:
1. The path you use must be the path of the shapefile, so don't use `Directory.GetCurrentDirectory() + "\\test` but use `Directory.GetCurrentDirectory() + "\\test\\myshapefile` (even better, use `Path.Combine` to make file paths)
2. Be sure that the folder exists, before writing a file on it, so something like `if !DirectoryExists(`Directory.GetCurrentDirectory() + "\\test) Directory.Create(`Directory.GetCurrentDirectory() + "\\test)`

**Comment by kronetix** [comment]
Thanks @DGuidi , an oversight on my part when tired.
I feel a bit silly.

**Comment by DGuidi** [comment]
welcome to the team 😉
