### ISSUE TITLE
How do I get the Feature Id?

### ISSUE THREAD

**Issue by mburbea** [NetTopologySuite/NetTopologySuite.IO.Esri#23]
I'm trying to upgrade a project that use to use the older NetTopologySuite.IO.ShapeFile. When I use to export a shape, I would get the esri generated Feature ID as the property "FeatureId". I've tried using GetOptionalId("FID") and GetOptionalId("FeatureID") and neither work.

**Comment by KubaSzostak** [comment]
The `FeatureId` it's not related to [Shapefile specification](https://www.esri.com/content/dam/esrisites/sitecore-archive/Files/Pdfs/library/whitepapers/pdfs/shapefile.pdf). You won't be able to find this attribute neither in `*.shp` nor in `*.dbf` file.

This is [specific](https://desktop.arcgis.com/en/arcmap/latest/manage-data/using-sql-with-gdbs/object-id.htm) to Esri software. The ObjectID is used by ArcGIS to do such things as scroll, display selection sets, and perform identify operations on features. To solve missing ObjectID in Shapefiles they used simple solution. They added virtual `FID` column where values start at zero. It's not real ID because if a record from a shapefile is deleted, the FIDs are renumbered so that they start from 0 and increase sequentially (there is no gap in numbering).

You can easily mimic the same:
```cs
var features = Shapefile.ReadAllFeatures(shpPath).ToList();
for (int featureId = 0; featureId < features.Count; featureId++)
{
    var feature = features[featureId];
    Console.WriteLine($"{"FID",10}: {featureId}");
    foreach (var attrName in feature.Attributes.GetNames())
    {
        Console.WriteLine($"{attrName,10}: {feature.Attributes[attrName]}");
    }
    Console.WriteLine($"     SHAPE: {feature.Geometry}");
    Console.WriteLine();
}
```

**Comment by mburbea** [comment]
Thank you for the explanation, I'll just use the array index as FID from now on.
