### ISSUE TITLE
How to write Shapefile header

### ISSUE THREAD

**Issue by xSandoval21x** [NetTopologySuite/NetTopologySuite.IO.Esri#24]
I have the NetTopologySuite.IO.Esri.Shapefile.WriteAllFeatures(features, path); working in my code. I have a requirement to set the Shapefile Header with file code, file length, version, shape type, Xmin, Ymin, Xmax, Ymax. Is there documentation on setting the file header with NetTopologySuite.IO.Esri?

**Comment by KubaSzostak** [comment]
All header values, for both SHP and SXH, are set by [ShpWriter](https://github.com/NetTopologySuite/NetTopologySuite.IO.Esri/blob/a2061ec5d03d9d789934521d1d7404e2c1ffbf2a/src/NetTopologySuite.IO.Esri.Shapefile/Shp/Writers/ShpWriter.cs#L88-L94) using [this](https://github.com/NetTopologySuite/NetTopologySuite.IO.Esri/blob/a2061ec5d03d9d789934521d1d7404e2c1ffbf2a/src/NetTopologySuite.IO.Esri.Shapefile/Shp/ShpStreamExtensions.cs#L13-L41) code. As you can see in the code all described above values are set. It seems like your requirement is already set.

If there is any problem with generated header please describe what exactly the issue is.

**Comment by xSandoval21x** [comment]
Thank you very much for pointing me to that code @KubaSzostak That's exactly what I needed.

**Comment by xSandoval21x** [comment]
@KubaSzostak Is there a way with the Shapefile Writer to write all files to a zip file?

**Comment by KubaSzostak** [comment]
> Is there a way with the Shapefile Writer to write all files to a zip file?

Sure. Use ZIP streams directly in `Shapefile*Writer` class [constructor](https://github.com/NetTopologySuite/NetTopologySuite.IO.Esri/blob/a2061ec5d03d9d789934521d1d7404e2c1ffbf2a/src/NetTopologySuite.IO.Esri.Shapefile/Shapefiles/Writers/ShapefilePointWriter.cs#L17-L19).
